### ISSUE TITLE
Blank nodes should be handled properly

### ISSUE THREAD

**Issue by ont-app** [ont-app/rdf#1]
There are cases where the RDF-based native representation of a graph we are dealing with will encode blank nodes. This is problematic for IGraph since it is non-trivial to translate such nodes into KWIs which can serve as persistent identifiers.

There are at least two solutions to this problem:
- create a normal graph (ont-app.igraph/graph/Graph) whose contents are a normal form translation of the contents of the RDF graph, using a simple one-time-only translation function for blank _:bnode123 -> :_/bnode123. This should be easy to code, but becomes a less attractive option as the graph gets larger.
- Materialize minted URIs linked to the original blank nodes somehow, coupled with queries which support this relation.

Done when:
- 
- default supporting query templates exclude blank nodes.
- there is a regime facilitating the materialization process described above.
- there is corresponding documentation, with tests.

See also: https://github.com/ont-app/igraph/issues/5

**Comment by ericdscott** [comment]
Fixed with https://github.com/ont-app/rdf/commit/11ae99efc00710eeecdfffa15d54b5cde3a7dd75
